import type { Metadata } from "next";
import ClientNav from "@/components/clientNav";
import Footer from "@/components/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className={`antialiased`}>
      <ClientNav />
      {children}
      <Footer />
    </div>
  );
}
